/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as MenuCodeRouteImport } from './routes/menu.$code'
import { Route as PagamentoCodeRouteImport } from './routes/pagamento.$code'
import { Route as VoucherCodeRouteImport } from './routes/voucher.$code'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminEquipeRouteImport } from './routes/_authenticated/admin.equipe'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated/admin.eventos'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminRelatoriosRouteImport } from './routes/_authenticated/admin.relatorios'
import { Route as AuthenticatedAdminRetiradaRouteImport } from './routes/_authenticated/admin.retirada'
import { Route as AuthenticatedAdminCardapiosIndexRouteImport } from './routes/_authenticated/admin.cardapios.index'
import { Route as AuthenticatedAdminCardapiosMenuIdRouteImport } from './routes/_authenticated/admin.cardapios.$menuId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MenuCodeRoute = MenuCodeRouteImport.update({
  id: '/menu/$code',
  path: '/menu/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoCodeRoute = PagamentoCodeRouteImport.update({
  id: '/pagamento/$code',
  path: '/pagamento/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const VoucherCodeRoute = VoucherCodeRouteImport.update({
  id: '/voucher/$code',
  path: '/voucher/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEquipeRoute =
  AuthenticatedAdminEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRelatoriosRoute =
  AuthenticatedAdminRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRetiradaRoute =
  AuthenticatedAdminRetiradaRouteImport.update({
    id: '/retirada',
    path: '/retirada',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCardapiosIndexRoute =
  AuthenticatedAdminCardapiosIndexRouteImport.update({
    id: '/cardapios/',
    path: '/cardapios/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCardapiosMenuIdRoute =
  AuthenticatedAdminCardapiosMenuIdRouteImport.update({
    id: '/cardapios/$menuId',
    path: '/cardapios/$menuId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/scanner': typeof ScannerRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/menu/$code': typeof MenuCodeRoute
  '/pagamento/$code': typeof PagamentoCodeRoute
  '/voucher/$code': typeof VoucherCodeRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/retirada': typeof AuthenticatedAdminRetiradaRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/cardapios/$menuId': typeof AuthenticatedAdminCardapiosMenuIdRoute
  '/admin/cardapios/': typeof AuthenticatedAdminCardapiosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/scanner': typeof ScannerRoute
  '/menu/$code': typeof MenuCodeRoute
  '/pagamento/$code': typeof PagamentoCodeRoute
  '/voucher/$code': typeof VoucherCodeRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/retirada': typeof AuthenticatedAdminRetiradaRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/cardapios/$menuId': typeof AuthenticatedAdminCardapiosMenuIdRoute
  '/admin/cardapios': typeof AuthenticatedAdminCardapiosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/scanner': typeof ScannerRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/menu/$code': typeof MenuCodeRoute
  '/pagamento/$code': typeof PagamentoCodeRoute
  '/voucher/$code': typeof VoucherCodeRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/_authenticated/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/_authenticated/admin/retirada': typeof AuthenticatedAdminRetiradaRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/cardapios/$menuId': typeof AuthenticatedAdminCardapiosMenuIdRoute
  '/_authenticated/admin/cardapios/': typeof AuthenticatedAdminCardapiosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/scanner'
    | '/admin'
    | '/menu/$code'
    | '/pagamento/$code'
    | '/voucher/$code'
    | '/admin/configuracoes'
    | '/admin/equipe'
    | '/admin/eventos'
    | '/admin/pedidos'
    | '/admin/relatorios'
    | '/admin/retirada'
    | '/admin/'
    | '/admin/cardapios/$menuId'
    | '/admin/cardapios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/scanner'
    | '/menu/$code'
    | '/pagamento/$code'
    | '/voucher/$code'
    | '/admin/configuracoes'
    | '/admin/equipe'
    | '/admin/eventos'
    | '/admin/pedidos'
    | '/admin/relatorios'
    | '/admin/retirada'
    | '/admin'
    | '/admin/cardapios/$menuId'
    | '/admin/cardapios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/scanner'
    | '/_authenticated/admin'
    | '/menu/$code'
    | '/pagamento/$code'
    | '/voucher/$code'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/equipe'
    | '/_authenticated/admin/eventos'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/relatorios'
    | '/_authenticated/admin/retirada'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/cardapios/$menuId'
    | '/_authenticated/admin/cardapios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ScannerRoute: typeof ScannerRoute
  MenuCodeRoute: typeof MenuCodeRoute
  PagamentoCodeRoute: typeof PagamentoCodeRoute
  VoucherCodeRoute: typeof VoucherCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/menu/$code': {
      id: '/menu/$code'
      path: '/menu/$code'
      fullPath: '/menu/$code'
      preLoaderRoute: typeof MenuCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/$code': {
      id: '/pagamento/$code'
      path: '/pagamento/$code'
      fullPath: '/pagamento/$code'
      preLoaderRoute: typeof PagamentoCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voucher/$code': {
      id: '/voucher/$code'
      path: '/voucher/$code'
      fullPath: '/voucher/$code'
      preLoaderRoute: typeof VoucherCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/equipe': {
      id: '/_authenticated/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthenticatedAdminEquipeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos': {
      id: '/_authenticated/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/relatorios': {
      id: '/_authenticated/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/retirada': {
      id: '/_authenticated/admin/retirada'
      path: '/retirada'
      fullPath: '/admin/retirada'
      preLoaderRoute: typeof AuthenticatedAdminRetiradaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cardapios/': {
      id: '/_authenticated/admin/cardapios/'
      path: '/cardapios'
      fullPath: '/admin/cardapios/'
      preLoaderRoute: typeof AuthenticatedAdminCardapiosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cardapios/$menuId': {
      id: '/_authenticated/admin/cardapios/$menuId'
      path: '/cardapios/$menuId'
      fullPath: '/admin/cardapios/$menuId'
      preLoaderRoute: typeof AuthenticatedAdminCardapiosMenuIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminEquipeRoute: typeof AuthenticatedAdminEquipeRoute
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminRelatoriosRoute: typeof AuthenticatedAdminRelatoriosRoute
  AuthenticatedAdminRetiradaRoute: typeof AuthenticatedAdminRetiradaRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCardapiosMenuIdRoute: typeof AuthenticatedAdminCardapiosMenuIdRoute
  AuthenticatedAdminCardapiosIndexRoute: typeof AuthenticatedAdminCardapiosIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminEquipeRoute: AuthenticatedAdminEquipeRoute,
  AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminRelatoriosRoute: AuthenticatedAdminRelatoriosRoute,
  AuthenticatedAdminRetiradaRoute: AuthenticatedAdminRetiradaRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCardapiosMenuIdRoute:
    AuthenticatedAdminCardapiosMenuIdRoute,
  AuthenticatedAdminCardapiosIndexRoute: AuthenticatedAdminCardapiosIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ScannerRoute: ScannerRoute,
  MenuCodeRoute: MenuCodeRoute,
  PagamentoCodeRoute: PagamentoCodeRoute,
  VoucherCodeRoute: VoucherCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
